### ISSUE TITLE
GPU가 일하는 시간을 더 늘릴 순 없을까요?

### ISSUE THREAD

**Issue by mun5mun4** [ORI-Muchim/One-Click-VITS-Training#1]
안녕하세요 덕분에 편하게 학습하고 있습니다.

글로벌 스텝은 8개씩 올라가고 이때 GPU가 사용되고 시간은 6초 걸립니다.

무언가 다른일을 하는 시간 15초가 걸립니다

GPU가 처리하는 시간보다 다른 무언가를 하는데 시간이 더 많이 드는데  GPU를 더 오래 지속적으로 사용하는 방법이 없을까요?

그러면 좀더 빠르게 학습이 될것 같습니다.

컴퓨터 사양은
CPU:13900K
RAM:128GB
GPU:RTX4090
OS:윈도우11
입니다

**Comment by ORI-Muchim** [comment]
윈도우에서 학습하면 GLOO를 사용해서 학습이 약간 느릴 수 있습니다. 우분투에서는 NCCL이라고 하는 라이브러리를 사용해서 훈련을 가속시킬 수 있습니다.

**Comment by ORI-Muchim** [comment]
또한, 데이터 양이 많지 않으면 에포크 정리 하는 시간이 길어져 학습 시간이 더 걸릴 수 있습니다.
